kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: deploy
    commands:
      - docker compose up -d --build --force-recreate
      - docker system prune -f -a
