services:
  securekey:
    image: fullstacklab/securekey
    container_name: securekey
    restart: unless-stopped
    build: .
    network_mode: traefik
    labels:
      traefik.enable: true
      traefik.http.services.securekey.loadbalancer.server.port: 3000
      traefik.http.routers.securekey.rule: Host(`securekey.fullstacklab.org`)
      traefik.http.routers.securekey.entrypoints: https
      traefik.http.routers.securekey.tls.certresolver: letsencrypt
